<HTML>
<HEAD>
<meta charset="UTF-8">
<title>AsyncResult.exceptional - cava</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">cava</a>&nbsp;/&nbsp;<a href="../index.html">net.consensys.cava.concurrent</a>&nbsp;/&nbsp;<a href="index.html">AsyncResult</a>&nbsp;/&nbsp;<a href="./exceptional.html">exceptional</a><br/>
<br/>
<h1>exceptional</h1>
<a name="net.consensys.cava.concurrent.AsyncResult$exceptional(kotlin.Throwable)"></a>
<code><span class="keyword">open</span> <span class="keyword">static</span> <span class="keyword">fun </span><span class="symbol">&lt;</span><span class="identifier">T</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-any/index.html"><span class="identifier">Any</span></a><span class="symbol">&gt;</span> <span class="identifier">exceptional</span><span class="symbol">(</span><span class="identifier" id="net.consensys.cava.concurrent.AsyncResult$exceptional(kotlin.Throwable)/ex">ex</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">)</span><span class="symbol">: </span><a href="index.html"><span class="identifier">AsyncResult</span></a><span class="symbol">&lt;</span><a href="exceptional.html#T"><span class="identifier">T</span></a><span class="symbol">&gt;</span></code> <a href="https://github.com/consensys/cava/blob/master//concurrent/src/main/java/net/consensys/cava/concurrent/AsyncResult.java#L57">(source)</a>
<p>Return an already failed result, caused by the given exception.</p>
<h3>Parameters</h3>
<p><a name="ex"></a>
<code>ex</code> - The exception.</p>
<p><a name="&lt;T&gt;"></a>
<code><T></code> - The type of the value that would be available if this result hadn't completed exceptionally.</p>
<p><strong>Return</strong><br/>
A failed result.</p>
</BODY>
</HTML>
